### ISSUE TITLE
.place thingtotype requires people to .thingtotype

### ISSUE THREAD

**Issue by s5bug** [BlobEmoji/coindrop#5]
![sc](https://wolfiri.hacked-your.webcam/7ea1fa7.png)

**Comment by Zeboto** [comment]
I think the bot should dm you and ask what to type. That way people can't copy from your message.

**Comment by s5bug** [comment]
Providing an image would be a cool way as well but would need for verification that the text matches the image. (Or the bot should generate an image)

**Comment by ivandardi** [comment]
We need to add a check to see if the suggested typing is fully ASCII and under 20 characters.

**Comment by max-kamps** [comment]
Obviously there should be some restrictions on the strings you can send it. No mentions etc.
I think disallowing non-alphabetical characters completely would be a good way to do that.

**Comment by scarletcafe** [comment]
Won't be implementing this as it allows users to spam, send offensive/NSFW content under the bot or create impossible sequences.

**Comment by IanMurray** [comment]
This doesn't seem like that great of a feature to be honest. If it was implemented however, it would have to be limited to ≈20 characters and alphanumerics.

**Comment by ivandardi** [comment]
Or offer the placer a few choices of `.commands` so that they can choose the one that will be used.

**Comment by 7bitlyrus** [comment]
I feel even with being able to specify what command to use from presets, this is unwise. Not only is it a minor feature with little use, but it could be used to manipulate coin transfer between individuals.
