### ISSUE TITLE
2 ideas

### ISSUE THREAD

**Issue by transmissions11** [BlobEmoji/coindrop#6]
1.
- Have an extended leader board, so instead of top 5, maybe a top 20 ish?

2.
- Each blob coin drop/place has an ID, and the id is given after the coin is taken
- If you run a command like .lookup [id] you can see the top 3 fastest people who were the fastest

Just ideas /shrug

**Comment by 7bitlyrus** [comment]
Please consider posting one idea per issue, thanks!

**Comment by transmissions11** [comment]
Oh sorry, didn't want to seem like I was spamming, so I combined issues 😨
