### ISSUE TITLE
Really easy to ghost ping

### ISSUE THREAD

**Issue by s5bug** [BlobEmoji/coindrop#9]
`.pick @personwhodoesntwanttobepinged`

**Comment by Xenthys** [comment]
I believe anyone being "ghost pinged" would complain about it, and the moderation log allows us to see who's abusing this. While this requires human intervention, this abuse is in the same category than people manually deleting their messages.

**Comment by scarletcafe** [comment]
This is not an issue with the bot. Any user could easily do this anyway either manually, or by saying an auto-censored word. As with all ghost pings, if people complain, we can check the logs and deal with them individually.
